example:
    resource: "@ExampleBundle/Resources/config/routing.yml"
    prefix:   /

application_sonata_admin:
    resource: "@ApplicationSonataAdminBundle/Resources/config/routing.yml"
    prefix:   /

application_user:
    resource: "@ApplicationUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media